<?php

wa('tasks');

class tasksMockNotificationsSender extends tasksNotificationsSender
{
    public $sent_map = array();

    public function prepareSendMap()
    {
        return parent::prepareSendMap();
    }

    public function send()
    {
        $this->sent_map = array();
        parent::send();
    }

    public function sendOne($type, $to_contact_id)
    {
        $this->sent_map[] = array($to_contact_id, $type);
    }

    public function checkNeedSentByAction($action, $settings)
    {
        return parent::checkNeedSentByAction($action, $settings); // TODO: Change the autogenerated stub
    }

    public function getContactsNotificationSettings($contact_id = null, $extra_contact_ids = array())
    {
        return parent::getContactsNotificationSettings($contact_id, $extra_contact_ids); // TODO: Change the autogenerated stub
    }

    public function getContactIdsNeedSentTo($action, $settings)
    {
        return parent::getContactIdsNeedSentTo($action, $settings); // TODO: Change the autogenerated stub
    }

    public function checkNeedSentByTask($contact_id, $settings)
    {
        return parent::checkNeedSentByTask($contact_id, $settings); // TODO: Change the autogenerated stub
    }
}
